
package pl.agh.soa.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyExchange", targetNamespace = "http://webservice.soa.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyExchange {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRate", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.GetRate")
    @ResponseWrapper(localName = "getRateResponse", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.GetRateResponse")
    public String getRate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sell", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.Sell")
    @ResponseWrapper(localName = "sellResponse", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.SellResponse")
    public String sell(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
