
package pl.agh.soa.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimeToHolidayImplService", targetNamespace = "http://webservice.soa.agh.pl/", wsdlLocation = "http://localhost:8081/TimeToHoliday/TimeToHoliday?wsdl")
public class TimeToHolidayImplService
    extends Service
{

    private final static URL TIMETOHOLIDAYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMETOHOLIDAYIMPLSERVICE_EXCEPTION;
    private final static QName TIMETOHOLIDAYIMPLSERVICE_QNAME = new QName("http://webservice.soa.agh.pl/", "TimeToHolidayImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/TimeToHoliday/TimeToHoliday?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMETOHOLIDAYIMPLSERVICE_WSDL_LOCATION = url;
        TIMETOHOLIDAYIMPLSERVICE_EXCEPTION = e;
    }

    public TimeToHolidayImplService() {
        super(__getWsdlLocation(), TIMETOHOLIDAYIMPLSERVICE_QNAME);
    }

    public TimeToHolidayImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMETOHOLIDAYIMPLSERVICE_QNAME, features);
    }

    public TimeToHolidayImplService(URL wsdlLocation) {
        super(wsdlLocation, TIMETOHOLIDAYIMPLSERVICE_QNAME);
    }

    public TimeToHolidayImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMETOHOLIDAYIMPLSERVICE_QNAME, features);
    }

    public TimeToHolidayImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeToHolidayImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeToHoliday
     */
    @WebEndpoint(name = "TimeToHolidayImplPort")
    public TimeToHoliday getTimeToHolidayImplPort() {
        return super.getPort(new QName("http://webservice.soa.agh.pl/", "TimeToHolidayImplPort"), TimeToHoliday.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeToHoliday
     */
    @WebEndpoint(name = "TimeToHolidayImplPort")
    public TimeToHoliday getTimeToHolidayImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.soa.agh.pl/", "TimeToHolidayImplPort"), TimeToHoliday.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMETOHOLIDAYIMPLSERVICE_EXCEPTION!= null) {
            throw TIMETOHOLIDAYIMPLSERVICE_EXCEPTION;
        }
        return TIMETOHOLIDAYIMPLSERVICE_WSDL_LOCATION;
    }

}
