
package pl.agh.soa.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeToHoliday", targetNamespace = "http://webservice.soa.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeToHoliday {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeToHoliday", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.GetTimeToHoliday")
    @ResponseWrapper(localName = "getTimeToHolidayResponse", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.GetTimeToHolidayResponse")
    @Action(input = "http://webservice.soa.agh.pl/TimeToHoliday/getTimeToHolidayRequest", output = "http://webservice.soa.agh.pl/TimeToHoliday/getTimeToHolidayResponse")
    public String getTimeToHoliday();

}
