
package pl.agh.webservice.string;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatisticalStringImplService", targetNamespace = "http://string.webservice.soa.agh.pl/", wsdlLocation = "http://localhost:8080/StatisticalStringServer/StatisticalStringImpl?wsdl")
public class StatisticalStringImplService
    extends Service
{

    private final static URL STATISTICALSTRINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATISTICALSTRINGIMPLSERVICE_EXCEPTION;
    private final static QName STATISTICALSTRINGIMPLSERVICE_QNAME = new QName("http://string.webservice.soa.agh.pl/", "StatisticalStringImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/StatisticalStringServer/StatisticalStringImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATISTICALSTRINGIMPLSERVICE_WSDL_LOCATION = url;
        STATISTICALSTRINGIMPLSERVICE_EXCEPTION = e;
    }

    public StatisticalStringImplService() {
        super(__getWsdlLocation(), STATISTICALSTRINGIMPLSERVICE_QNAME);
    }

    public StatisticalStringImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATISTICALSTRINGIMPLSERVICE_QNAME, features);
    }

    public StatisticalStringImplService(URL wsdlLocation) {
        super(wsdlLocation, STATISTICALSTRINGIMPLSERVICE_QNAME);
    }

    public StatisticalStringImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATISTICALSTRINGIMPLSERVICE_QNAME, features);
    }

    public StatisticalStringImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatisticalStringImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatisticalString
     */
    @WebEndpoint(name = "StatisticalStringImplPort")
    public StatisticalString getStatisticalStringImplPort() {
        return super.getPort(new QName("http://string.webservice.soa.agh.pl/", "StatisticalStringImplPort"), StatisticalString.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatisticalString
     */
    @WebEndpoint(name = "StatisticalStringImplPort")
    public StatisticalString getStatisticalStringImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://string.webservice.soa.agh.pl/", "StatisticalStringImplPort"), StatisticalString.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATISTICALSTRINGIMPLSERVICE_EXCEPTION!= null) {
            throw STATISTICALSTRINGIMPLSERVICE_EXCEPTION;
        }
        return STATISTICALSTRINGIMPLSERVICE_WSDL_LOCATION;
    }

}
