
package pl.agh.webservice.string;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatisticalString", targetNamespace = "http://string.webservice.soa.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatisticalString {


    /**
     * 
     * @param yourString
     * @return
     *     returns pl.agh.webservice.string.AnalyseStringResponse.ReturnedHashMap
     */
    @WebMethod
    @WebResult(name = "returnedHashMap", targetNamespace = "")
    @RequestWrapper(localName = "analyseString", targetNamespace = "http://string.webservice.soa.agh.pl/", className = "pl.agh.webservice.string.AnalyseString")
    @ResponseWrapper(localName = "analyseStringResponse", targetNamespace = "http://string.webservice.soa.agh.pl/", className = "pl.agh.webservice.string.AnalyseStringResponse")
    public pl.agh.webservice.string.AnalyseStringResponse.ReturnedHashMap analyseString(
        @WebParam(name = "yourString", targetNamespace = "")
        String yourString);

}
