
package pl.agh.webservice2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FirstWebService", targetNamespace = "http://webservice2.soa.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirstWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns pl.agh.webservice2.AddTwoNumbersResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "addTwoNumbers", targetNamespace = "http://webservice2.soa.agh.pl/", className = "pl.agh.webservice2.AddTwoNumbers")
    @ResponseWrapper(localName = "addTwoNumbersResponse", targetNamespace = "http://webservice2.soa.agh.pl/", className = "pl.agh.webservice2.AddTwoNumbersResponse")
    public pl.agh.webservice2.AddTwoNumbersResponse.Return addTwoNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
